<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>xuu0w-01fvm-001.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Asset\starry-sky-2051448_1280.jpg" />
    <None Remove="Asset\xuu0w-01fvm-001.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Asset\starry-sky-2051448_1280.jpg" />
    <Resource Include="Asset\xuu0w-01fvm-001.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="C:\Users\yylyh\Downloads\starry-sky-2051448_1280.jpg" Link="Asset\starry-sky-2051448_1280.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="xuu0w-01fvm-001.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
	  <PackageReference Include="NLog.Extensions.Logging" Version="6.1.3" />
	  <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
	  <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
	  <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
	  <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlcMonitor.Core\PlcMonitor.Core.csproj" />
  </ItemGroup>

</Project>
